
import { Inter } from "next/font/google";
import '@fortawesome/fontawesome-svg-core/styles.css'
import "./globals.css";
import Link from "next/link";
import HomePageNavBar from "@/components/NavBar/HomePageNavBar";
import ReduxProvider from "@/components/reduxProvider";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex h-screen w-screen bg-black text-white">
        <ReduxProvider>
          <HomePageNavBar />
          <div className="flex w-full">
            {children}
          </div>
          </ReduxProvider>
      </body>
    </html>
  );
}
